### ISSUE TITLE
Tooltip does not closed correctly

### ISSUE THREAD

**Issue by rifaldhiaw** [jsartisan/react-native-magnus#36]
Thank you for the awesome library.   
I am using this lib, for my personal projects (web and mobile.)   

I want to use the tooltip component for my web layout. 
But there is a weird behavior that happens when I try to close the tooltip (click anywhere).

- Click once -> toolip showing back
- Double click -> tooltip hidden

It seems there is a state race/something like that. Thank you...

![captured](https://user-images.githubusercontent.com/7936061/101000339-5a364180-3590-11eb-8be0-61a114bc102f.gif)

**Comment by jsartisan** [comment]
Thanks a lot for the reporting. I will be releasing a new version tonight. Hoping to fix this one also in that :D

**Comment by jsartisan** [comment]
@rifaldhiaw Fixed in v1.0.54. Can you verify on your end?

**Comment by rifaldhiaw** [comment]
Awesome, it works well now...   
Thank you so much \(^ヮ^)/

**Comment by rifaldhiaw** [comment]
Uhh umm.. just 1 minor thing, it seems you forgot to update the types declaration path in `package.json` to    
`"types": "lib/typescript/src/index.d.ts",`. (nested in src folder).   


Thanks :D

**Comment by jsartisan** [comment]
Thanks for the PR :)

Updated it in v1.0.55
